### ISSUE TITLE
split_dataset_1和split_dataset_2有啥区别？

### ISSUE THREAD

**Issue by gw-zhong** [Teng-Sun/CLUE_model#2]
在MOSI中，存在这样两个数据集，split_dataset_1、split_dataset_2，在MOSEI中，也有original_dataset、split_dataset_2，在split_dataset_1和original_dataset里也有test_OOD的文件，所以不是很清楚，这两者的区别在哪里？论文里实验用的是哪个？

**Comment by Teng-Sun** [comment]
具体设置请仔细阅读在config.py设置文件。因为2分类和7分类的偏差是不同的，所以我们特意分开构造两个数据集。MOSEI中 split_dataset_2 是 2 分类数据集，split_dataset_7classes_1 是 7分类数据集。MOSI 中 split_dataset_2 是 2 分类数据集，split_dataset_7classes_1 是 7分类数据集。

**Comment by gw-zhong** [comment]
谢谢您能在百忙之中回答！还有一个疑问，就是在data_loader.py中，若base_model是'magbert_model'的话，为什么NEW_SENT_LEN依然等于原先的SENT_LEN？但add_special_tokens又一直是True，所以没太懂这里序列长度设置和其他模型不一样的原因，是因为magbert不需要加[CLS]和[SEP]吗？

**Comment by gw-zhong** [comment]
你好，我想问一下上传的数据集是否存在一些问题？我注意到，在MOSI的数据集中，无论是「split_dataset_2」还是「split_dataset_7classes_1」，其文件夹下的「test_IID.pkl」和「test_OOD.pkl」均一模一样。而在MOSEI中则没有出现这种情况。
如下所示，是「MOSI」数据集中「split_dataset_2」文件夹里，「test_IID.pkl」和「test_OOD.pkl」的视频id输出：
<img width="575" alt="图片" src="https://user-images.githubusercontent.com/61236543/215312770-566e0af1-1f0d-446f-8fd7-ad562f9f0550.png">
同样的，在「MOSI」七分类的文件夹「split_dataset_7classes_1」里，「test_IID.pkl」和「test_OOD.pkl」的视频id也保持一致：
<img width="554" alt="图片" src="https://user-images.githubusercontent.com/61236543/215312942-37779bba-9944-4d43-974c-02d323bfed4f.png">
而对于「MOSEI」数据集而言，只有在「original_dataset」中会出现这种情况，在「split_dataset_2」和「split_dataset_7classes_1」里，IID和OOD的分布是不一样的。
所以，能否把正确的「MOSI」数据集上传？

**Comment by gw-zhong** [comment]
我认为「MOSI」数据集缺失的是否是IID部分？因为dev上得到的精度与这些测试集上得到的精度相差较多

**Comment by Conyrol** [comment]
MOSI 由于整体数据量小，数据集涉及视频数也很少，构造偏差时难以像 MOSEI 一样有充分的样本数划分为4个子数据集，所以没有专门的 test_IID.pkl，只有 test_OOD.pkl，我们在MOSI的测试上使用 valid 和 iid_test 统一的方式来衡量指标，之所以现在上传的版本 test_IID.pkl 和 test_OOD.pkl 一致，主要是为了保证读取数据部分的代码能正常运行，这个部分在代码中应该有解释

**Comment by Conyrol** [comment]
> 我认为「MOSI」数据集缺失的是否是IID部分？因为dev上得到的精度与这些测试集上得到的精度相差较多

MOSI 由于整体数据量小，数据集涉及视频数也很少，构造偏差时难以像 MOSEI 一样有充分的样本数划分为4个子数据集，所以没有专门的 test_IID.pkl，只有 test_OOD.pkl，我们在MOSI的测试上使用 valid 和 iid_test 统一的方式来衡量指标，之所以现在上传的版本 test_IID.pkl 和 test_OOD.pkl 一致，主要是为了保证读取数据部分的代码能正常运行，这个部分在代码中应该有解释

至于 dev 上得到的精度与这些测试集上得到的精度相差较多是正常现象，因为测试集相对于验证集是构造的偏差数据集，所以一定会有精度上的区别。
